_target_: src.models.gigaPose.GigaPose
model_name: large
log_interval: 1000
log_dir: ${save_dir}

defaults:
  - ae_net: dinov2_l
  - ist_net: resnet

testing_metric:
  _target_: src.models.matching.LocalSimilarity
  k: 5
  sim_threshold: 0.5
  patch_threshold: 3

checkpoint_path: ${machine.root_dir}/pretrained/gigaPose_v1.ckpt
